---
- name: config | configuring filebeat
  template:
    src: etc/filebeat/filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - restart filebeat
  become: true
