---
- name: redhat | Adding filebeat Repo Key
  rpm_key:
    key: "{{ es_filebeat_repo_key }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: redhat | Adding filebeat Repo
  yum_repository:
    baseurl: "{{ es_filebeat_repo_url+'/'+es_filebeat_major_ver+'/yum' }}"
    description: "Filebeat repository for {{ es_filebeat_major_ver }} packages"
    enabled: true
    gpgcheck: true
    gpgkey: "{{ es_filebeat_repo_key }}"
    name: "{{ 'filebeat-'+es_filebeat_major_ver }}"
    state: present
  become: true

- name: redhat | Installing filebeat
  package:
    name: "{{ 'filebeat-'+es_filebeat_minor_version|string }}"
    state: present
  become: true
  register: result
  until: result is successful
