---
- name: redhat | installing pre-reqs
  yum:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'unzip'
  when: ansible_distribution != "Fedora"

- name: redhat | downloading filebeat
  get_url:
    url: "{{ es_filebeat_dl_url }}/{{ es_filebeat_redhat_package }}"
    dest: "/opt/{{ es_filebeat_redhat_package }}"

- name: redhat | installing filebeat
  yum:
    name: "/opt/{{ es_filebeat_redhat_package }}"
    state: "present"
  when: ansible_distribution != "Fedora"
